name: "Build eda-modbus-bridge"

on: [ push, pull_request ]

jobs:
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  build:
    name: Build eda-modbus-bridge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build eda-modbus-bridge
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target eda-modbus-bridge
