name: "Build eda-modbus-bridge"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build eda-modbus-bridge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [armhf, armv7, amd64, aarch64, i386]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build eda-modbus-bridge (${{ matrix.architecture }})
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target eda-modbus-bridge
